---

- name: Install postgis
  apt:
    name:
      - postgis

- name: Setup PostgreSQL service
  service:
    name: postgresql
    state: started
    enabled: yes

- name: Setup pg_hba.conf
  template:
    src: templates/pg_hba.conf.j2
    dest: /etc/postgresql/{{ postgresql_version }}/main/pg_hba.conf
  notify: Restart postgresql

- name: Create /etc/postgresql/{{ postgresql_version }}/main/conf.d/tuning.conf
  template:
    src: templates/tuning.conf.j2
    dest: /etc/postgresql/{{ postgresql_version }}/main/conf.d/tuning.conf
  notify: Restart postgresql

- name: Restart PostgreSQL if pg_hba.conf has changed
  meta: flush_handlers

- name: Setup master
  include_role:
    name: postgresql
    tasks_from: setup_master
  when: setup_master

- name: Setup slave
  include_role:
    name: postgresql
    tasks_from: setup_slave
  when: setup_slave
