---

- name: Install postgis and pgbouncer
  apt:
    name:
      - postgis
      - pgbouncer

- name: Setup PostgreSQL service
  service:
    name: postgresql
    state: started
    enabled: yes

- name: Setup pgbouncer service
  service:
    name: pgbouncer
    state: started
    enabled: yes

- name: Setup pgbouncer/pgbouncer.ini
  template:
    src: templates/pgbouncer.ini.j2
    dest: /etc/pgbouncer/pgbouncer.ini
    owner: postgres
    group: postgres
    mode: 0640
  notify: Restart pgbouncer

- name: Setup pgbouncer/userlist.txt
  template:
    src: templates/userlist.txt.j2
    dest: /etc/pgbouncer/userlist.txt
    owner: postgres
    group: postgres
    mode: 0640

- name: Setup pg_hba.conf
  template:
    src: templates/pg_hba.conf.j2
    dest: /etc/postgresql/{{ postgresql.version }}/main/pg_hba.conf
  notify: Restart postgresql

- name: Create /etc/postgresql/{{ postgresql.version }}/main/conf.d/tuning.conf
  template:
    src: templates/tuning.conf.j2
    dest: /etc/postgresql/{{ postgresql.version }}/main/conf.d/tuning.conf
  notify: Restart postgresql

- name: Restart PostgreSQL if pg_hba.conf has changed
  meta: flush_handlers

- name: Setup master
  include_role:
    name: postgresql
    tasks_from: setup_master
  when: postgresql.setup_master

- name: Setup slave
  include_role:
    name: postgresql
    tasks_from: setup_slave
  when: postgresql.setup_slave
