---

- name: Setup initial master
  include_role:
    name: postgresql
    tasks_from: setup_master_initial
  when: setup_initial

- name: Create /etc/postgresql/{{ postgresql_version }}/main/conf.d/replication.conf
  template:
    src: templates/replication.conf.j2
    dest: /etc/postgresql/{{ postgresql_version }}/main/conf.d/replication.conf
  notify: Restart postgresql

- name: Start PostgreSQL
  systemd:
    name: postgresql
    state: started
