---

- name: Setup initial master
  include_role:
    name: postgresql
    tasks_from: setup_master_initial
  when: postgresql.setup_initial

- name: Create /etc/postgresql/{{ postgresql.version }}/main/conf.d/replication.conf
  template:
    src: templates/replication.conf.j2
    dest: /etc/postgresql/{{ postgresql.version }}/main/conf.d/replication.conf
  notify: Restart postgresql

- name: Start PostgreSQL
  systemd:
    name: postgresql
    state: started

- name: CREATE ROLE {{ deploy.api_taxi.postgresql.username }}
  shell: >
    sudo -u postgres psql -c "
      SET password_encryption = 'scram-sha-256';
      CREATE ROLE {{ deploy.api_taxi.postgresql.username }} WITH LOGIN PASSWORD '{{ deploy.api_taxi.postgresql.password }}';
    " || echo "Role {{ deploy.api_taxi.postgresql.username }} already exists"
