---
# Recreate PostgreSQL slave from master

- name: stat /data/postgresql/{{ postgresql.version }}
  stat:
    path: /data/postgresql/{{ postgresql.version }}
  register: datadir

- fail:
    msg: /data/postgresql/{{ postgresql.version }} already exists. If you really want to create a slave on this server, remove the directory manually before running this role.
  when: datadir.stat.exists

- name: Stop PostgreSQL
  systemd:
    name: postgresql
    state: stopped

- name: Create /etc/postgresql/{{ postgresql.version }}/main/conf.d/slave.conf
  template:
    src: templates/slave.conf
    dest: /etc/postgresql/{{ postgresql.version }}/main/conf.d/slave.conf

- name: Create directory /data/postgresql/{{ postgresql.version }}/main
  file:
    path: /data/postgresql/{{ postgresql.version }}/main
    state: directory
    recurse: true
    mode: '0700'

- name: Remove directory /var/lib/postgresql/{{ postgresql.version }}
  file:
    path: /var/lib/postgresql/{{ postgresql.version }}
    state: absent

- name: Create symlink /data/postgresql/{{ postgresql.version}} /var/lib/postgresql/{{ postgresql.version }}
  file:
    src: /data/postgresql/{{ postgresql.version }}
    dest: /var/lib/postgresql/{{ postgresql.version }}
    state: link

- name: Call pg_basebackup
  command: pg_basebackup -h {{ postgresql_master }} -D /var/lib/postgresql/{{ postgresql.version }}/main/ -P -U replicate --wal-method=stream
  environment:
    PGPASSWORD: "{{ postgresql.replication_password }}"

- name: Create /var/lib/postgresql/{{ postgresql.version }}/main/recovery.conf
  template:
    src: templates/recovery.conf.j2
    dest: /var/lib/postgresql/{{ postgresql.version }}/main/recovery.conf
    mode: '0600'

- name: chown /data/postgresql/ to postgres:postgres
  file:
    path: /data/postgresql/
    owner: postgres
    group: postgres
    recurse: yes
    state: directory
