---

- name: Install nginx and certbot
  apt:
    name:
      - nginx
      - certbot
      - python3-certbot-nginx
      - python3-passlib

- name: Create /var/www/html/5xx.html
  template:
    src: templates/5xx.html
    dest: /var/www/html/5xx.html

- name: Make sure /etc/nginx/sites-enabled/default is absent
  file:
    path: /etc/nginx/sites-enabled/default
    state: absent
  notify: Reload nginx

- name: Setup /etc/nginx/sites-enabled/default.conf
  template:
    src: templates/default.conf.j2
    dest: /etc/nginx/sites-enabled/default.conf
  notify: Reload nginx

- name: Setup /etc/nginx/sites-enabled/api-taxi.conf
  template:
    src: templates/api-taxi.conf.j2
    dest: /etc/nginx/sites-enabled/api-taxi.conf
  notify: Reload nginx

- name: Setup /etc/nginx/sites-enabled/api-taxi-console.conf
  template:
    src: templates/api-taxi-console.conf.j2
    dest: /etc/nginx/sites-enabled/api-taxi-console.conf
  notify: Reload nginx

- name: Setup /etc/nginx/sites-enabled/grafana.conf
  template:
    src: templates/grafana.conf.j2
    dest: /etc/nginx/sites-enabled/grafana.conf
  notify: Reload nginx

- name: Setup /etc/nginx/sites-enabled/celery-flower.conf
  template:
    src: templates/celery-flower.conf.j2
    dest: /etc/nginx/sites-enabled/celery-flower.conf
  notify: Reload nginx

- name: Disable server tokens
  template:
    src: templates/tokens.conf
    dest: /etc/nginx/conf.d/tokens.conf
  notify: Reload nginx

- htpasswd:
    path: /etc/nginx/admin.passwd
    name: "{{ item.username }}"
    password: '{{ item.password }}'
    owner: root
    group: www-data
    mode: 0640
  with_items: "{{ nginx.admin_users }}"

- stat: path=/etc/letsencrypt/live/{{ deploy.hostname }}
  register: letsencrypt_deploy_directory

- fail:
    msg: "Letsencrypt certificates must be installed manually for {{ deploy.hostname }}. Run `certbot --nginx`, or copy them from the master server (if this machine is the slave). If this is a first installation, you might need to comment SSL configuration from nginx conf."
  when: not letsencrypt_deploy_directory.stat.exists

- stat: path=/etc/letsencrypt/live/{{ grafana.hostname }}
  register: letsencrypt_grafana_directory

- fail:
    msg: "Letsencrypt certificates must be installed manually for {{ grafana.hostname }}. Run `certbot --nginx`, or copy them from the master server (if this machine is the slave). If this is a first installation, you might need to comment SSL configuration from nginx conf."
  when: not letsencrypt_grafana_directory.stat.exists
