---

- name: Install nginx and certbot
  apt:
    name:
      - nginx
      - certbot
      - python3-certbot-nginx
      - python3-passlib

- stat: path=/etc/letsencrypt/live/{{ deploy.hostname }}
  register: letsencrypt_directory

- fail:
    msg: "Letsencrypt certificates must be installed manually for {{ deploy.hostname }}. Run `certbot --nginx`, or copy them from the master server (if this machine is the slave)."
  when: not letsencrypt_directory.stat.exists

- name: Generate /etc/ssl/dhparams.pem
  openssl_dhparam:
    path: /etc/ssl/dhparam.pem
  notify: Reload nginx

- name: Remove default nginx configuration file
  file:
    path: /etc/nginx/sites-enabled/default
    state: absent
  notify: Reload nginx

- name: Setup /etc/nginx/sites-enabled/api-taxi.conf
  template:
    src: templates/api-taxi.conf.j2
    dest: /etc/nginx/sites-enabled/api-taxi.conf
  notify: Reload nginx

- htpasswd:
    path: /etc/nginx/admin.passwd
    name: "{{ item.username }}"
    password: '{{ item.password }}'
    owner: root
    group: www-data
    mode: 0640
  with_items: "{{ nginx.admin_users }}"
