---

- name: Create directory /opt/openmaraude/api_taxi
  file:
    path: /opt/openmaraude/api_taxi
    state: directory

- name: Setup /opt/openmaraude/api_taxi/uwsgi.ini
  template:
    src: templates/api_taxi/uwsgi.ini.j2
    dest: /opt/openmaraude/api_taxi/uwsgi.ini
  vars:
    python_module: APITaxi

- name: Setup /opt/openmaraude/api_taxi/settings.py
  template:
    src: templates/api_taxi/settings.py.j2
    dest: /opt/openmaraude/api_taxi/settings.py

- name: Setup /opt/openmaraude/api_taxi/api_taxi.env
  template:
    src: templates/api_taxi/api_taxi.env.j2
    dest: /opt/openmaraude/api_taxi/api_taxi.env
  vars:
    docker_image: "{{ api_taxi.docker.image }}"
    docker_image_version: "{{ api_taxi.docker.version }}"

- name: Create directory /var/lib/api_taxi
  file:
    path: /var/lib/api_taxi
    state: directory

- name: Create directory /var/lib/api_taxi/uploads
  file:
    path: /var/lib/api_taxi/uploads
    state: directory
    mode: '0777'

- name: Setup APITaxi systemd service file
  template:
    src: templates/api_taxi/api_taxi.service.j2
    dest: /etc/systemd/system/api_taxi.service
  vars:
    project: api_taxi
    host_port: 8427
    host_port_stats: 8428
  notify:
    - Reload systemd

- name: Setup APITaxi worker systemd service file
  template:
    src: templates/api_taxi/{{ item }}.service
    dest: /etc/systemd/system/{{ item }}.service
  notify:
    - Reload systemd
  with_items:
    - api_taxi_worker
    - api_taxi_stat_worker
    - api_taxi_beat_worker
    - celery_flower

# Required to run handlers now because if file has changed, we want the new
# file to take effect before the restart, and not after.
- name: Reload systemd if configuration file has changed
  meta: flush_handlers

# Restart is always mandatory to pull the latest version
- name: Enable and start (or restart) api_taxi service
  systemd:
    name: "api_taxi"
    enabled: yes
    state: restarted

- name: Enable and start (or restart) api_taxi_worker service (if redis master)
  systemd:
    name: "{{ item }}"
    enabled: yes
    state: restarted
  when: redis.role == 'master'
  with_items:
    - api_taxi_worker
    - api_taxi_stat_worker
    - api_taxi_beat_worker
    - celery_flower

# Worker fails to start on redis slave.
- name: Disable and stop api_taxi_worker service (if redis slave)
  systemd:
    name: "{{ item }}"
    enabled: no
    state: stopped
  when: redis.role == 'slave'
  with_items:
    - api_taxi_worker
    - api_taxi_stat_worker
    - api_taxi_beat_worker
    - celery_flower
