---

- name: Create directory /opt/openmaraude/api_taxi_front
  file:
    path: /opt/openmaraude/api_taxi_front
    state: directory

- name: Setup /opt/openmaraude/api_taxi_front/uwsgi.ini
  template:
    src: templates/api_taxi/uwsgi.ini.j2
    dest: /opt/openmaraude/api_taxi_front/uwsgi.ini
  vars:
    python_module: APITaxi_front

- name: Setup /opt/openmaraude/api_taxi_front/settings.py
  template:
    src: templates/api_taxi/settings.py.j2
    dest: /opt/openmaraude/api_taxi_front/settings.py
  vars:
    hostname: "console.{{ deploy.hostname }}"

- name: Setup /opt/openmaraude/api_taxi_front/api_taxi_front.env
  template:
    src: templates/api_taxi/api_taxi.env.j2
    dest: /opt/openmaraude/api_taxi_front/api_taxi_front.env
  vars:
    docker_image: "{{ api_taxi_front.docker.image }}"
    docker_image_version: "{{ api_taxi_front.docker.version }}"

- name: Create directory /var/lib/api_taxi
  file:
    path: /var/lib/api_taxi
    state: directory

- name: Create directory /var/lib/api_taxi/uploads
  file:
    path: /var/lib/api_taxi/uploads
    state: directory
    mode: '0777'

- name: Setup systemd service file
  template:
    src: templates/api_taxi/api_taxi.service.j2
    dest: /etc/systemd/system/api_taxi_front.service
  vars:
    project: api_taxi_front
    host_port: 8327
    host_port_stats: 8328
  notify:
    - Reload systemd

# Required to run handlers now because if file has changed, we want the new
# file to take effect before the restart, and not after.
- name: Reload systemd if configuration file has changed
  meta: flush_handlers

# Restart is always mandatory to pull the latest version
- name: Enable and start (or restart) api_taxi_front service
  systemd:
    name: "api_taxi_front"
    enabled: yes
    state: restarted
