---

- name: Create directory /opt/openmaraude/api_taxi_swagger
  file:
    path: /opt/openmaraude/api_taxi_swagger
    state: directory

- name: Setup /opt/openmaraude/api_taxi_swagger/params.env
  template:
    src: templates/api_taxi_swagger/api_taxi_swagger.env.j2
    dest: /opt/openmaraude/api_taxi_swagger/api_taxi_swagger.env

- name: Setup systemd service file
  template:
    src: templates/api_taxi_swagger/api_taxi_swagger.service
    dest: /etc/systemd/system/api_taxi_swagger.service
  notify:
    - Reload systemd

# Required to run handlers now because if file has changed, we want the new
# file to take effect before the restart, and not after.
- name: Reload systemd if configuration file has changed
  meta: flush_handlers

# Restart is always mandatory to pull the latest version
- name: Enable and start (or restart) api_taxi_swagger service
  systemd:
    name: api_taxi_swagger
    enabled: yes
    state: restarted
