---

- name: Create directory /opt/openmaraude/api_taxi_tester
  file:
    path: /opt/openmaraude/api_taxi_tester
    state: directory

- name: Setup /opt/openmaraude/api_taxi_tester/uwsgi.ini
  template:
    src: templates/api_taxi/uwsgi.ini.j2
    dest: /opt/openmaraude/api_taxi_tester/uwsgi.ini
  vars:
    python_module: APITaxi_tester.front.app

- name: Setup /opt/openmaraude/api_taxi_tester/settings.py
  template:
    src: templates/api_taxi/settings.py.j2
    dest: /opt/openmaraude/api_taxi_tester/settings.py

- name: Setup /opt/openmaraude/api_taxi_tester/api_taxi_tester.env
  template:
    src: templates/api_taxi/api_taxi.env.j2
    dest: /opt/openmaraude/api_taxi_tester/api_taxi_tester.env
  vars:
    docker_image: "{{ api_taxi_tester.docker.image }}"
    docker_image_version: "{{ api_taxi_tester.docker.version }}"

- name: Setup systemd service file
  template:
    src: templates/api_taxi/api_taxi.service.j2
    dest: /etc/systemd/system/api_taxi_tester.service
  vars:
    project: api_taxi_tester
    host_port: 8627
    host_port_stats: 8628
    mount_upload_dir: no
  notify:
    - Reload systemd

# Required to run handlers now because if file has changed, we want the new
# file to take effect before the restart, and not after.
- name: Reload systemd if configuration file has changed
  meta: flush_handlers

# Restart is always mandatory to pull the latest version
- name: Enable and start (or restart) api_taxi_tester service
  systemd:
    name: "api_taxi_tester"
    enabled: yes
    state: restarted
