---

# File imported from main.yml, {{ project }} should be "api_taxi" or "api_taxi_front".

- name: Create directory /opt/openmaraude/{{ project }}
  file:
    path: /opt/openmaraude/{{ project }}
    state: directory

- name: Setup /opt/openmaraude/{{ project }}/uwsgi.ini
  template:
    src: templates/api_taxi/uwsgi.ini
    dest: /opt/openmaraude/{{ project }}/uwsgi.ini

# Used settings from api_taxi
- name: Setup /opt/openmaraude/{{ project }}/settings.py
  template:
    src: templates/api_taxi/settings.py.j2
    dest: /opt/openmaraude/{{ project }}/settings.py

- name: Setup /opt/openmaraude/{{ project }}/{{ project }}.env
  template:
    src: templates/api_taxi/api_taxi.env
    dest: /opt/openmaraude/{{ project }}/{{ project }}.env

# /var/lib/api_taxi is the host directory mounted in containers to store
# uploaded files. This directory is shared for api_taxi and api_taxi_front.
- name: Create directory /var/lib/api_taxi
  file:
    path: /var/lib/api_taxi
    state: directory

- name: Create directory /var/lib/api_taxi/uploads
  file:
    path: /var/lib/api_taxi/uploads
    state: directory
    mode: '0777'

- name: Setup systemd service file
  template:
    src: templates/api_taxi/api_taxi.service
    dest: /etc/systemd/system/{{ project }}.service
  notify:
    - Reload systemd

# Required to run handlers now because if file has changed, we want the new
# file to take effect before the restart, and not after.
- name: Reload systemd if configuration file has changed
  meta: flush_handlers

# Restart is always mandatory to pull the latest version
- name: Enable and start (or restart) {{ project }} service
  systemd:
    name: "{{ project }}"
    enabled: yes
    state: restarted
