---

- name: Create directory /opt/openmaraude/console
  file:
    path: /opt/openmaraude/console
    state: directory

- name: Setup /opt/openmaraude/console/console.env
  template:
    src: templates/console/console.env.j2
    dest: /opt/openmaraude/console/console.env
  vars:
    docker_image: "{{ console.docker.image }}"
    docker_image_version: "{{ console.docker.version }}"

- name: Setup systemd service file
  template:
    src: templates/console/console.service.j2
    dest: /etc/systemd/system/console.service
  notify:
    - Reload systemd

# Required to run handlers now because if file has changed, we want the new
# file to take effect before the restart, and not after.
- name: Reload systemd if configuration file has changed
  meta: flush_handlers

# Restart is always mandatory to pull the latest version
- name: Enable and start (or restart) console service
  systemd:
    name: "console"
    enabled: yes
    state: restarted
