---

- name: Setup systemd service file
  template:
    src: templates/geotaxi/geotaxi.service
    dest: /etc/systemd/system/geotaxi.service
  notify:
    - Reload systemd

- name: Create directory /opt/openmaraude/geotaxi
  file:
    path: /opt/openmaraude/geotaxi
    state: directory

- name: Setup /opt/openmaraude/geotaxi/params.env
  template:
    src: templates/geotaxi/geotaxi.env.j2
    dest: /opt/openmaraude/geotaxi/geotaxi.env

# Required to run handlers now because if file has changed, we want the new
# file to take effect before the restart, and not after.
- name: Reload systemd if configuration file has changed
  meta: flush_handlers

# Restart is always mandatory to pull the latest version
- name: Enable and start (or restart) geotaxi service
  systemd:
    name: geotaxi
    enabled: yes
    state: restarted
