---

- name: Import role to deploy geotaxi
  include_role:
    name: deploy
    tasks_from: geotaxi
  when: geotaxi.deploy

- name: Import role to deploy APITaxi_front
  include_role:
    name: deploy
    tasks_from: api_taxi_front.yml
  when: api_taxi_front.deploy

- name: Import role to deploy APITaxi
  include_role:
    name: deploy
    tasks_from: api_taxi.yml
  when: api_taxi.deploy

- name: Import role to deploy map
  include_role:
    name: deploy
    tasks_from: map.yml
  when: map.deploy
