---

- name: Import role to deploy geotaxi
  include_role:
    name: deploy
    tasks_from: geotaxi
  when: geotaxi.deploy

- name: Import role to deploy APITaxi_front
  include_role:
    name: deploy
    tasks_from: api_taxi_front.yml
  when: api_taxi_front.deploy

- name: Import role to deploy APITaxi
  include_role:
    name: deploy
    tasks_from: api_taxi.yml
  when: api_taxi.deploy

- name: Import role to deploy APITaxi_swagger
  include_role:
    name: deploy
    tasks_from: api_taxi_swagger.yml
  when: api_taxi_swagger.deploy

- name: Import role to deploy map
  include_role:
    name: deploy
    tasks_from: map.yml
  when: map.deploy

- name: Import role to deploy geofaker
  include_role:
    name: deploy
    tasks_from: geofaker
  when: geofaker.deploy

- name: Import role to deploy minimal_operateur_server
  include_role:
    name: deploy
    tasks_from: minimal_operateur_server
  when: deploy.dev_environment and minimal_operateur_server.deploy
