---

- name: Import role to deploy geotaxi
  include_role:
    name: deploy
    tasks_from: geotaxi
  when: geotaxi.deploy

- name: Import role to deploy APITaxi_front
  include_role:
    name: deploy
    tasks_from: api_taxi_front.yml
  when: api_taxi_front.deploy
