---

# Required for postgresql_db
- name: Install python3-psycopg2
  package:
    name:
      - python3-psycopg2
  when: postgresql.role == 'master'

- name: Create database grafana
  become: true
  become_user: postgres
  postgresql_db:
    name: grafana
  when: postgresql.role == 'master'

- name: Setup grafana
  include_role:
    name: cloudalchemy.grafana
  vars:
    grafana_url: "https://{{ grafana.hostname }}"
    grafana_instance: "{{ grafana.hostname }}"
    # Should the provisioning be kept synced. If true, previous provisioned objects will be removed if not referenced anymore.
    grafana_provisioning_synced: true

    grafana_database:
      type: postgres
      host: "{{ postgresql.master }}:5432"
      user: "{{ grafana.postgresql.username }}"
      password: "{{ grafana.postgresql.password }}"
      name: grafana

    grafana_security:
      admin_user: "{{ grafana.admin_username }}"
      admin_password: "{{ grafana.admin_password }}"

    grafana_smtp:
      enabled: true
      from_address: grafana@api.taxi
