---

- hosts: all
  roles:
    - common
    - network
    - firewall
    - monitoring

- hosts:
    - taxis01
    - taxis02
  roles:
    - fluent
    - influx
    - nginx

# Install postgresql/redis master
- hosts:
    - taxis01
  roles:
    - postgresql
    - redis

# Install postgresql/redis slave
- hosts:
    - taxis02
  roles:
    - postgresql
    - redis

# Install barman
- hosts:
    - taxis03
  roles:
    - barman

# Grafana needs PostgreSQL
- hosts:
    - taxis01
  roles:
    - grafana

# Install first on master (to create database), then on slave
- hosts:
  - taxis02:
  roles:
    - grafana
