- name: Uninstall netplan
  package:
    name: netplan.io
    state: absent

# For some reasons, it might be necessary to run
# `systemctl enable systemd-networkd` manually because the statement below
# doesn't work on first install...
# It might be related to https://github.com/ansible/ansible/issues/39116
- name: Enable systemd-networkd
  systemd:
    name: systemd-networkd
    enabled: yes

- name: Create network configuration for {{ network.public.iface }}
  template:
    src: templates/etc/systemd/network/public_iface.network.j2
    dest: /etc/systemd/network/{{ network.public.iface }}.network
  notify: Restart systemd-networkd

- name: Create directory where move-failover-ips.sh stores failover configuration files
  file:
    path: /etc/systemd/network/{{ network.public.iface }}.network.d
    state: directory
    mode: '0755'
  when: network.setup_failover

- name: Create GRE net device {{ network.private.iface }}
  template:
    src: templates/etc/systemd/network/private_iface.netdev.j2
    dest: /etc/systemd/network/{{ network.private.iface }}.netdev
  notify: Restart systemd-networkd
  when: network.private.setup_gre

- name: Create network configuration for {{ network.private.iface }}
  template:
    src: templates/etc/systemd/network/private_iface.network.j2
    dest: /etc/systemd/network/{{ network.private.iface }}.network
  notify: Restart systemd-networkd

- name: Create systemd-netword .netdev file for {{ network.private.iface }}.{{ network.private.vlan }}
  template:
    src: templates/etc/systemd/network/private_iface.vlan.netdev.j2
    dest: /etc/systemd/network/{{ network.private.iface }}.{{ network.private.vlan }}.netdev
  notify: Restart systemd-networkd

- name: Create network configuration for {{ network.private.iface }}.{{ network.private.vlan }}
  template:
    src: templates/etc/systemd/network/private_iface.vlan.network.j2
    dest: /etc/systemd/network/{{ network.private.iface }}.{{ network.private.vlan }}.network
  notify: Restart systemd-networkd

- name: Create /etc/dhcp/dhclient6-failover.conf
  template:
    src: templates/etc/dhcp/dhclient6-failover.conf.j2
    dest: /etc/dhcp/dhclient6-failover.conf
  when: network.setup_failover

- name: Create /etc/systemd/system/dhclient6-failover.service
  template:
    src: templates/etc/systemd/system/dhclient6-failover.service.j2
    dest: /etc/systemd/system/dhclient6-failover.service
  when: network.setup_failover

- name: Disable service dhclient6-failover (since this server is not master). dhclient6-failover service is dynamically enabled from move-failover-ips.sh
  systemd:
    name: dhclient6-failover
    daemon-reload: yes
    enabled: no
  when: network.setup_failover and network.failover.ipv4.addr not in ansible_all_ipv4_addresses

- name: Enable service dhclient6-failover (since this server is the master)
  systemd:
    name: dhclient6-failover
    daemon-reload: yes
    enabled: yes
  when: network.setup_failover and network.failover.ipv4.addr in ansible_all_ipv4_addresses

- name: Create /opt/openmaraude/network directory
  file:
    path: /opt/openmaraude/network
    state: directory
    mode: '0755'
  when: network.setup_failover

- name: Create /opt/openmaraude/network/move-failover-ips.sh
  template:
    src: templates/opt/openmaraude/network/move-failover-ips.sh.j2
    dest: /opt/openmaraude/network/move-failover-ips.sh
    mode: '0700'
  when: network.setup_failover

- debug: msg="On first run, you need to reboot to have the GRE tunnel working"
  when: network.private.setup_gre
