- name: Check required variables
  fail: msg="Variable '{{ item }}' is not defined"
  when: item not in vars
  with_items: "{{ required_vars }}"

- name: Check required failover variables
  fail: msg="Variable '{{ item }}' is not defined"
  when: setup_failover and item not in vars
  with_items: "{{ required_failover_vars }}"

- name: Uninstall netplan
  package:
    name: netplan.io
    state: absent

- name: Enable systemd-networkd
  systemd:
    name: systemd-networkd
    enabled: yes

- name: Create network configuration for {{ public_iface }}
  template:
    src: templates/etc/systemd/network/public_iface.network.j2
    dest: /etc/systemd/network/{{ public_iface }}.network
  notify: Restart systemd-networkd

- name: Create directory where move-failover-ips.sh stores failover configuration files
  file:
    path: /etc/systemd/network/{{ public_iface }}.network.d
    state: directory
    mode: '0755'
  when: setup_failover

- name: Create network configuration for {{ private_iface }}
  template:
    src: templates/etc/systemd/network/private_iface.network.j2
    dest: /etc/systemd/network/{{ private_iface }}.network
  notify: Restart systemd-networkd

- name: Create systemd-netword .netdev file for {{ private_iface }}.{{ private_vlan }}
  template:
    src: templates/etc/systemd/network/private_iface.vlan.netdev.j2
    dest: /etc/systemd/network/{{ private_iface }}.{{ private_vlan }}.netdev
  notify: Restart systemd-networkd

- name: Create network configuration for {{ private_iface }}.{{ private_vlan }}
  template:
    src: templates/etc/systemd/network/private_iface.vlan.network.j2
    dest: /etc/systemd/network/{{ private_iface }}.{{ private_vlan }}.network
  notify: Restart systemd-networkd

- name: Create /etc/dhcp/dhclient6-failover.conf
  template:
    src: templates/etc/dhcp/dhclient6-failover.conf.j2
    dest: /etc/dhcp/dhclient6-failover.conf
  when: setup_failover

- name: Create /etc/systemd/system/dhclient6-failover.service
  template:
    src: templates/etc/systemd/system/dhclient6-failover.service.j2
    dest: /etc/systemd/system/dhclient6-failover.service
  when: setup_failover

- name: Disable service dhclient6-failover (service is dynamically enabled from move-failover-ips.sh)
  systemd:
    name: dhclient6-failover
    daemon-reload: yes
    enabled: no
  when: setup_failover

- name: Create /opt/openmaraude/network directory
  file:
    path: /opt/openmaraude/network
    state: directory
    mode: '0755'
  when: setup_failover

- name: Create /opt/openmaraude/network/move-failover-ips.sh
  template:
    src: templates/opt/openmaraude/network/move-failover-ips.sh.j2
    dest: /opt/openmaraude/network/move-failover-ips.sh
    mode: '0700'
  when: setup_failover
