---

- name: Install ufw
  apt:
    name:
      - ufw

- name: Reset UFW
  ufw:
    state: reset

- name: Set logging to low
  ufw:
    logging: 'low'

- name: Allow outgoing
  ufw:
    direction: outgoing
    policy: allow

- name: Allow all from 10.0.0.0/8
  ufw:
    rule: allow
    src: 10.0.0.0/8

- name: Allow all from containers network 172.30.0.0/24
  ufw:
    rule: allow
    src: 172.30.0.0/24

- name: Allow SSH
  ufw:
    rule: allow
    name: OpenSSH

- name: Allow HTTP
  ufw:
    rule: allow
    port: http

- name: Allow HTTPS
  ufw:
    rule: allow
    port: https

- name: "{{ item.description }}"
  ufw:
    rule: "{{ item.rule }}"
    port: "{{ item.port }}"
    src: "{{ item.src }}"
  with_items: "{{ firewall.extra_rules }}"

- name: Allow incoming traffic for DHCPv6
  ufw:
    rule: allow
    port: 546

- name: Reject incoming
  ufw:
    direction: incoming
    policy: reject

- name: Enable UFW
  ufw:
    state: enabled
