"
" This file is installed by Ansible. ** DO NOT ** edit manually.
"
colorscheme desert
syntax on

set showmatch
set paste
set ruler
set showmode
set undolevels=2000
set autoindent
set history=500
set wildmenu
set incsearch
set hlsearch
set mouse=a
set scrolloff=10
set autochdir
set nolist
set number
set expandtab

" show line cursor
"set cursorline
"set cursorcolumn
autocmd ColorScheme *
    \ hi CursorLine term=none cterm=underline ctermbg=0 |
    \ hi CursorColumn term=none cterm=none ctermbg=DarkGrey

" Show trailing whitespaces
autocmd ColorScheme *
    \ highlight WhitespaceEOL ctermbg=red |
    \ match WhitespaceEOL /\s\+$/
autocmd WinEnter * match WhiteSpaceEOL /\s\+$/

" >> tabstop
"    Set tabstop to tell vim how many columns a tab counts for. Linux kernel
"    code expects each tab to be eight columns wide. Visual Studio expects
"    each tab to be four columns wide. This is the only command here that will
"    affect how existing text displays.
"
" >> expandtab
"    When expandtab is set, hitting Tab in insert mode will produce the
"    appropriate number of spaces.
"
" >> shiftwidth
"    Set shiftwidth to control how many columns text is indented with the
"    reindent operations (<< and >>) and automatic C-style indentation.
"
" >> softtabstop
"    Set softtabstop to control how many columns vim uses when you hit Tab in
"    insert mode. If softtabstop is less than tabstop and expandtab is not
"    set, vim will use a combination of tabs and spaces to make up the desired
"    spacing. If softtabstop equals tabstop and expandtab is not set, vim will
"    always use tabs. When expandtab is set, vim will always use the
"    appropriate number of spaces.

au BufNewFile,BufRead *.sls set filetype=yaml " Detect Salt sls files as YAML

au FileType yaml set expandtab softtabstop=2 tabstop=2 shiftwidth=2
au FileType python set expandtab softtabstop=4 tabstop=4 shiftwidth=4 textwidth=79
