---

- name: Install Python dependencies
  package:
    name: [
      "python-virtualenv",
      "python3-pip",
      "git"
     ]

- name: Install APITaxi dependencies
  package:
    name: [
    "libffi-dev",
    "libgeos-dev",
    "libpq-dev"
  ]

- name: Remove virtualenv {{ api_taxi_virtualenv }}
  file:
    state: absent
    path: "{{ api_taxi_virtualenv }}"
  when: api_taxi_recreate_virtualenv

- name: Install APITaxi packages in virtualenv {{ api_taxi_virtualenv }} - {{ api_taxi_repositories }}
  pip:
    name: "{{ api_taxi_repositories }}"
    virtualenv: "{{ api_taxi_virtualenv }}"
