---

- name: Install Python dependencies
  package:
    name: [
      "python-virtualenv",
      "python3-pip",
      "git",
      "uwsgi-plugin-python3"
     ]

- name: Install APITaxi dependencies
  package:
    name: [
    "libffi-dev",
    "libgeos-dev",
    "libpq-dev"
  ]

- name: Remove virtualenv {{ api_taxi_virtualenv }}
  file:
    state: absent
    path: "{{ api_taxi_virtualenv }}"
  when: api_taxi_recreate_virtualenv

- name: Install APITaxi packages in virtualenv {{ api_taxi_virtualenv }} - {{ api_taxi_repositories }}
  pip:
    name: "{{ api_taxi_repositories }}"
    virtualenv: "{{ api_taxi_virtualenv }}"

- name: Install extra Python packages in virtualenv {{ api_taxi_virtualenv }}
  pip:
    name:
      - uwsgitop
    virtualenv: "{{ api_taxi_virtualenv }}"

- name: Install uWSGI
  package:
    name: uwsgi-emperor

- name: Start uwsgi-emperor
  service:
    name: uwsgi-emperor
    enabled: yes
    state: started

- name: Create uwsgi-emperor vassal configuration
  template:
    src: templates/api-taxi.ini.j2
    dest: /etc/uwsgi-emperor/vassals/api-taxi.ini
