---

- name: Create systemd service file
  template:
    src: templates/api-taxi.service.j2
    dest: /etc/systemd/system/api-taxi.service
  notify:
    - Reload systemd unit files
    - Restart api-taxi

- name: Creates directory /etc/openmaraude
  file:
    path: /etc/openmaraude
    state: directory

- name: Creates directory /var/run/openmaraude
  file:
    path: /var/run/openmaraude
    state: directory
    # Container needs to write socket files in this directory
    mode: '0777'

- name: Create api-taxi uWSGI configuration file
  template:
    src: templates/api-taxi.ini
    dest: /etc/openmaraude/api-taxi.ini
  notify: Restart api-taxi

# If variable api_taxi_restart is true, force a restart
- name: Force api-taxi restart
  command: /bin/true
  notify: Restart api-taxi
  when: api_taxi_restart

- name: Enable api-taxi.service
  service:
    name: api-taxi
    state: started
    enabled: yes
